var x = 5;
x++; 
console.log("After increment: " + x);
x--;  
console.log("After decrement: " + x);
var a = 7;
var b = 5;
console.log("a == b: ", a == b);
console.log("a != b: ", a != b);
console.log("a === b: ", a === b);
console.log("a !== b: ", a !== b);
console.log("a > b: ", a > b);
console.log("a < b: ", a < b);
console.log("a >= b: ", a >= b);
console.log("a <= b: ", a <= b);